# OpenSSLConfig.cmake for Android
# This file tells CMake where to find the precompiled OpenSSL for Android
# Generated by TsVitch build system

set(OPENSSL_FOUND TRUE)
set(OPENSSL_VERSION "3.3.2")

# These paths are relative to the JNI directory (android-project/app/jni/)
# ANDROID_PROJECT_LIBS_DIR is set by the JNI CMakeLists.txt
if(DEFINED ANDROID_PROJECT_LIBS_DIR)
    set(_OPENSSL_LIBS_DIR "${ANDROID_PROJECT_LIBS_DIR}/${ANDROID_ABI}")
    set(_OPENSSL_INCLUDE_DIR "${ANDROID_PROJECT_LIBS_DIR}/../jni/openssl/include")
else()
    get_filename_component(_OPENSSL_JNI_DIR "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
    set(_OPENSSL_LIBS_DIR "${_OPENSSL_JNI_DIR}/../libs/${ANDROID_ABI}")
    set(_OPENSSL_INCLUDE_DIR "${CMAKE_CURRENT_LIST_DIR}/include")
endif()

set(OPENSSL_INCLUDE_DIR "${_OPENSSL_INCLUDE_DIR}" CACHE PATH "" FORCE)
set(OPENSSL_CRYPTO_LIBRARY "${_OPENSSL_LIBS_DIR}/libcrypto.so" CACHE FILEPATH "" FORCE)
set(OPENSSL_SSL_LIBRARY "${_OPENSSL_LIBS_DIR}/libssl.so" CACHE FILEPATH "" FORCE)
set(OPENSSL_LIBRARIES "${OPENSSL_SSL_LIBRARY};${OPENSSL_CRYPTO_LIBRARY}")

if(NOT TARGET OpenSSL::Crypto)
    add_library(OpenSSL::Crypto SHARED IMPORTED)
    set_target_properties(OpenSSL::Crypto PROPERTIES
        IMPORTED_LOCATION "${OPENSSL_CRYPTO_LIBRARY}"
        INTERFACE_INCLUDE_DIRECTORIES "${OPENSSL_INCLUDE_DIR}"
    )
endif()

if(NOT TARGET OpenSSL::SSL)
    add_library(OpenSSL::SSL SHARED IMPORTED)
    set_target_properties(OpenSSL::SSL PROPERTIES
        IMPORTED_LOCATION "${OPENSSL_SSL_LIBRARY}"
        INTERFACE_INCLUDE_DIRECTORIES "${OPENSSL_INCLUDE_DIR}"
        INTERFACE_LINK_LIBRARIES "OpenSSL::Crypto"
    )
endif()
